### PR TITLE
Parse this: Tue Feb 16 2016 17:23:34 GMT+0800

### PR DESCRIPTION
**Pull request by zhangao0086**
This PR contains parsing the broken format `Tue Feb 16 2016 17:23:34 GMT+0800`.

### CODE REVIEW

**Comment by dinhviethoa** [comment]
Could you create a new function instead?
mailimf_hack_date_time_parse()

Then in MailCore, MessageHeader::importIMAPEnvelope(), use:

```
void MessageHeader::importIMAPEnvelope(struct mailimap_envelope * env)
{
    if (env->env_date != NULL) {
        size_t cur_token;
        struct mailimf_date_time * date_time;
        int r;

        cur_token = 0;
        r = mailimf_date_time_parse(env->env_date, strlen(env->env_date),
            &cur_token, &date_time);
        if (r == MAILIMF_NO_ERROR) {
            time_t timestamp;

            // date
            timestamp = timestampFromDate(date_time);
            setDate(timestamp);
            setReceivedDate(timestamp);
            mailimf_date_time_free(date_time);
        }

        if (r != MAILIMF_NO_ERROR) {
            r = mailimf_hack_date_time_parse(env->env_date, strlen(env->env_date),
            &cur_token, &date_time);
            if (r == MAILIMAP_NO_ERROR) {
                time_t timestamp;

                timestamp = timestampFromDate(imap_date);
                setDate(timestamp);
                setReceivedDate(timestamp);
                mailimf_date_time_free(date_time);
            }
        }

        if (r != MAILIMF_NO_ERROR) {
            struct mailimap_date_time * imap_date;

            r = mailimap_hack_date_time_parse(env->env_date, &imap_date, 0, NULL);
            if (r == MAILIMAP_NO_ERROR) {
                time_t timestamp;

                timestamp = timestampFromIMAPDate(imap_date);
                setDate(timestamp);
                setReceivedDate(timestamp);
                mailimap_date_time_free(imap_date);
            }
        }
    }

    ...
```

**Comment by zhangao0086** [comment]
In my case, the `MessageHeader::importIMAPEnvelope` function is never getting called...

**Comment by dinhviethoa** [comment]
ah ok, you're fetching the full header.
Could you still have a separate mailimf_hack_date_time_parse() and call it in mailimf_date_time_parse() if it fails to parse the date (on MAILIMF_ERROR_PARSE)?

Basically, you would replace calls to `return r` to `res = r; goto err;` and in the label 'err:`, you would call the workaround mailimf_hack_date_time_parse() if there's a parse error.

**Comment by zhangao0086** [comment]
Updated. Please review again.

**Comment by zhangao0086** [comment]
Any problems?

**Comment by dinhviethoa** [comment]
I'm taking a closer look at the code to see the best way to do it.

**Comment by zhangao0086** [comment]
I believe you have a better way :)

**Comment by dinhviethoa** [comment]
I'm not sure. Anyway, the code you provided here is very useful.

**Comment by dinhviethoa** [comment]
I eventually used something similar to the first commit. Thanks!

**Pull request closed without merging**
