### PR TITLE
workaround for a bug of qq.com server

### PR DESCRIPTION
**Pull request by shenmin**
https://github.com/MailCore/mailcore2/issues/1029

### CODE REVIEW

**Comment by shenmin** [comment]
Now make it a workaround for qq only.

**Comment by dinhviethoa** [comment]
Do you have an account where I can test it?
Thanks.

**Comment by shenmin** [comment]
Yes, I have sent the account to your gmail.

**Comment by dinhviethoa** [comment]
Could you try this branch? I implemented a workaround for qqmail.

https://github.com/dinhviethoa/libetpan/tree/qqmail-envelope

Let me know if everything work smoothly for you before I merge it in the main repository.

**Comment by shenmin** [comment]
It works fine here. :)

**Comment by dinhviethoa** [comment]
It's great! I'm merging my change to the main repository then!

**Comment by dinhviethoa** [comment]
Thanks for your analyze and test data!

**Comment by luohaiquan** [comment]
All right

**Pull request closed without merging**
